FROM --platform=$BUILDPLATFORM redhat/ubi10-minimal:10.1@sha256:7bd3d2e7f5c507aebd1575d0f2fab9fe3e882e25fee54fa07f7970aa8bbc5fab

USER root
COPY entrypoint-redhat.sh /entrypoint
ENTRYPOINT [ "/entrypoint" ]
