FROM --platform=$BUILDPLATFORM debian:stable@sha256:37ad77961af28800b00f5f96a4dfda1855bdcf87f8431033f8b6a549d825bba3

RUN apt-get update && apt-get install -y ca-certificates --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint-debian.sh /entrypoint
ENTRYPOINT [ "/entrypoint" ]
