FROM --platform=$BUILDPLATFORM debian:bookworm

RUN apt-get update && apt-get install -y ca-certificates --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint-debian.sh /entrypoint
ENTRYPOINT [ "/entrypoint" ]
