{{- if and .Values.externalSecret .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.caSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    clusterScoped: {{ .Values.externalSecret.secretStore.clusterScoped }}
  target:
    name: {{ .Values.caSecret.name }}
data:
  - secretKey: {{ .Values.caSecret.key }}
    remoteRef:
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: {{ .Values.externalSecret.remoteRef.property }}
{{- else if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.caSecret.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
spec:
  commonName: {{ .Values.dummyCertificate.domainName }}
  usages:
    - server auth
  duration: 8760h0m0s # 1y
  dnsNames:
    - {{ .Values.dummyCertificate.domainName }}
  secretName: {{ .Values.caSecret.name }}
  issuerRef:
    {{- toYaml .Values.dummyCertificate.issuer | nindent 4}}
  privateKey:
    size: 4096
{{- else if .Values.caSecret.value -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caSecret.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
data:
  {{ .Values.caSecret.key }}: |
    {{ .Values.caSecret.value }}
{{- end }}
