---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cain.servingCertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "cain.labels" . | nindent 4 }}
spec:
  commonName: {{ include "cain.fullname" . }}
  usages:
    - server auth
  duration: 8760h0m0s # 1y
  dnsNames:
    - {{ include "cain.fullname" . }}
    - {{ include "cain.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "cain.fullname" . }}.{{ .Release.Namespace }}.svc
  secretName: {{ include "cain.servingCertificate" . }}
  issuerRef:
    {{- if .Values.externalIssuer }}
    {{- toYaml .Values.externalIssuer | nindent 4}}
    {{- else }}
    name: {{ include "cain.rootCAIssuer" . }}
    {{- end }}
  privateKey:
    size: 4096