apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cain.serviceAccountName" . }}-get-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
rules:
- apiGroups:
    - "" # "" indicates the core API group
  resources:
    - secrets
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cain.serviceAccountName" . }}-create-delete
  labels:
    {{- include "cain.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
  verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cain.serviceAccountName" . }}-get
  labels:
    {{- include "cain.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
- apiGroups:
    - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
    - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cain.serviceAccountName" . }}-get-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cain.serviceAccountName" . }}-get-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "cain.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cain.serviceAccountName" . }}-create-delete
  labels:
    {{- include "cain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cain.serviceAccountName" . }}-create-delete
subjects:
  - kind: ServiceAccount
    name: {{ include "cain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cain.serviceAccountName" . }}-get
  labels:
    {{- include "cain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cain.serviceAccountName" . }}-get
subjects:
  - kind: ServiceAccount
    name: {{ include "cain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
