apiVersion: v1
kind: Service
metadata:
  name: {{ include "cain.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook-api
  selector:
    {{- include "cain.selectorLabels" . | nindent 4 }}
