---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cain.fullname" . }}
  {{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cain.servingCertificate" . }}
  {{- end }}
  labels:
    {{- include "cain.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "cain.fullname" . }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "cain.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/inject/validate"
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
        - CREATE
        - DELETE
        resources:
          - pods
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
          - kube-system
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
    failurePolicy: Fail
    matchPolicy: Equivalent
    objectSelector:
      matchExpressions:
      - key: cain.{{ .Values.config.metadataDomain }}/enabled
        operator: Exists

