---
apiVersion: "v1"
kind: ServiceAccount
metadata:
  name: {{ include "ca-injector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-get-secrets"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-create-delete"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
    - "create"
    - "delete"
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-get"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources:
  - "deployments"
  - "replicasets"
  - "statefulsets"
  - "daemonsets"
  verbs: ["get"]
- apiGroups: ["batch"]
  resources:
  - "jobs"
  - "cronjobs"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-get-secrets"
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "ca-injector.serviceAccountName" . }}-get-secrets"
subjects:
  - kind: ServiceAccount
    name: "{{ include "ca-injector.serviceAccountName" . }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-create-delete"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "ca-injector.serviceAccountName" . }}-create-delete"
subjects:
  - kind: ServiceAccount
    name: "{{ include "ca-injector.serviceAccountName" . }}"
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ca-injector.labels" (dict "context" . "component" "webhook") | nindent 4 }}
  name: "{{ include "ca-injector.serviceAccountName" . }}-get"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "ca-injector.serviceAccountName" . }}-get"
subjects:
  - kind: ServiceAccount
    name: "{{ include "ca-injector.serviceAccountName" . }}"
    namespace: {{ .Release.Namespace }}