name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'deploy/charts/**'
  push:
    paths:
      - 'deploy/charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.17.3
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ${{ github.workspace }}/ct.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ${{ github.workspace }}/ct.yaml --target-branch ${{ github.event.repository.default_branch }}
      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-image-tag
        if: steps.list-changed.outputs.changed == 'true'
        with:
          semver_only: true
      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install \
          --config ${{ github.workspace }}/ct.yaml \
          --helm-extra-set-args "--set=image.tag=${{ steps.get-latest-image-tag.outputs.tag }}" \
          --target-branch ${{ github.event.repository.default_branch }}
