name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  attestations: write
  packages: write

jobs:
  go-release:
    name: Release images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable']
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
          initial_version: v0.0.0

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: 'CAIn ${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - name: Set up Go
        if: ${{ steps.release-label.outputs.level != null }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Login to GitHub Container Registry
        if: ${{ steps.release-label.outputs.level != null }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ko image
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make publish

      - name: Publish init images
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make all-init
  helm-release:
    name: Release chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}
        with:
          label_prefix: chart/
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-image-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
      - uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        id: get-previous-chart-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          prefix: chart/
          fallback: 0.0.0
      - id: chart-previous-semver
        run: |
          CHART_SEMVER=$(echo ${{ steps.get-previous-chart-tag.outputs.tag }} | cut -d/ -f2)
          echo "tag=${CHART_SEMVER}">>${GITHUB_OUTPUT}
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.chart-previous-semver.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: chart/${{ steps.bump-semver.outputs.new_version }}
          message: 'CAIn Chart chart/${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
      - name: Login to GitHub Container Registry
        if: ${{ steps.release-label.outputs.level != null }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm chart
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.get-latest-image-tag.outputs.tag }}
          CHART_VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make publish-chart
