name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  attestations: write
  packages: write

jobs:
  go-release:
    name: Release images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions-ecosystem/action-release-label@1c7ef83d383a57bf253a2e2e9dfe1b55f445ae15 # v1.2.0
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
          initial_version: v0.0.0

      - uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f # v1.0.0
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: 'CAIn ${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - name: Set up Go
        if: ${{ steps.release-label.outputs.level != null }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Login to GitHub Container Registry
        if: ${{ steps.release-label.outputs.level != null }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ko image
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make publish

      - name: Publish init images
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make all-init
  helm-release:
    name: Release chart
    runs-on: ubuntu-latest
    needs: go-release
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions-ecosystem/action-release-label@1c7ef83d383a57bf253a2e2e9dfe1b55f445ae15 # v1.2.0
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}
        with:
          label_prefix: chart/
      - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
        id: get-latest-image-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
      - uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0
        id: get-previous-chart-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          pattern: chart/*
          fallback: 0.0.0
      - id: chart-previous-semver
        run: |
          CHART_SEMVER=$(echo ${{ steps.get-previous-chart-tag.outputs.tag }} | cut -d/ -f2)
          echo "tag=${CHART_SEMVER}">>${GITHUB_OUTPUT}
      - uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.chart-previous-semver.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f # v1.0.0
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: chart/${{ steps.bump-semver.outputs.new_version }}
          message: 'CAIn Chart chart/${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
      - name: Login to GitHub Container Registry
        if: ${{ steps.release-label.outputs.level != null }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm chart
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          VERSION: ${{ steps.get-latest-image-tag.outputs.tag }}
          CHART_VERSION: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          make publish-chart
